=== SarvarKh/Coursework-Weather-XML/src/main/resources/weather.dtd
<!ELEMENT countries (country+) >
<!ELEMENT country (cities) >
<!ELEMENT cities (city+) >
<!ELEMENT city (days) >
<!ELEMENT days (day+) >
<!ELEMENT day (temperature, humidity, wind-speed) >
<!ELEMENT temperature (min, max) >
<!ELEMENT min (#PCDATA) >
<!ELEMENT max (#PCDATA) >
<!ELEMENT humidity (min, max)>
<!ELEMENT wind-speed (min, max)>


<!ATTLIST country name CDATA #REQUIRED>
<!ATTLIST city name CDATA #REQUIRED>
<!ATTLIST day name CDATA #REQUIRED>
<!ATTLIST temperature unit CDATA #REQUIRED>
<!ATTLIST humidity unit CDATA #REQUIRED>
<!ATTLIST wind-speed unit CDATA #REQUIRED>

=== SarvarKh/Coursework-Weather-XML/src/main/resources/weather.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE countries SYSTEM "weather.dtd">
<?xml-stylesheet type="text/xml" href="weather.xsl" version="1.0"?>
<countries>
    <country name="United Kingdom">
        <cities>
            <city name="London">
                <days>
                    <day name="Monday">
                        <temperature unit="°C">
                            <min>13.0</min>
                            <max>13.5</max>
                        </temperature>
                        <humidity unit="%">
                            <min>89</min>
                            <max>91</max>
                        </humidity>
                        <wind-speed unit="km/h">
                            <min>13</min>
                            <max>15</max>
                        </wind-speed>
                    </day>
                    <day name="Tuesday">
                        <temperature unit="°C">
                            <min>13.5</min>
                            <max>14.5</max>
                        </temperature>
                        <humidity unit="%">
                            <min>85</min>
                            <max>90</max>
                        </humidity>
                        <wind-speed unit="km/h">
                            <min>12</min>
                            <max>14</max>
                        </wind-speed>
                    </day>
                </days>
            </city>
            <city name="London">
                <days>
                    <day name="Monday">
                        <temperature unit="°C">
                            <min>13.0</min>
                            <max>13.5</max>
                        </temperature>
                        <humidity unit="%">
                            <min>89</min>
                            <max>91</max>
                        </humidity>
                        <wind-speed unit="km/h">
                            <min>13</min>
                            <max>15</max>
                        </wind-speed>
                    </day>
                    <day name="Tuesday">
                        <temperature unit="°C">
                            <min>13.5</min>
                            <max>14.5</max>
                        </temperature>
                        <humidity unit="%">
                            <min>85</min>
                            <max>90</max>
                        </humidity>
                        <wind-speed unit="km/h">
                            <min>12</min>
                            <max>14</max>
                        </wind-speed>
                    </day>
                </days>
            </city>
        </cities>
    </country>
    <country name="Poland">
        <cities>
            <city name="London">
                <days>
                    <day name="Monday">
                        <temperature unit="°C">
                            <min>13.0</min>
                            <max>13.5</max>
                        </temperature>
                        <humidity unit="%">
                            <min>89</min>
                            <max>91</max>
                        </humidity>
                        <wind-speed unit="km/h">
                            <min>13</min>
                            <max>15</max>
                        </wind-speed>
                    </day>
                    <day name="Tuesday">
                        <temperature unit="°C">
                            <min>13.5</min>
                            <max>14.5</max>
                        </temperature>
                        <humidity unit="%">
                            <min>85</min>
                            <max>90</max>
                        </humidity>
                        <wind-speed unit="km/h">
                            <min>12</min>
                            <max>14</max>
                        </wind-speed>
                    </day>
                </days>
            </city>
        </cities>
    </country>
</countries>
